modules:
  networking:
    terraform_dir: ../environments/dev/tests/01-networking
    tests:
      - test_networking

  security_groups:
    terraform_dir: ../environments/dev/tests/02-security-groups
    tests:
      - test_security_groups

  storage:
    terraform_dir: ../environments/dev/tests/03-storage
    tests:
      - test_s3


  messaging:
    terraform_dir: ../environments/dev/tests/04-messaging
    tests:
      - test_sqs


  # api:
  #   terraform_dir: ../environments/dev/api-only
  #   tests:
  #     - test_api



  # storage-messaging:
  #   terraform_dir: ../environments/dev/storage-messaging
  #   tests:
  #     - test_storage_messaging



  # worker:
  #   terraform_dir: ../environments/dev/worker-only
  #   tests:
  #     - test_worker

  # full-pipeline:
  #   terraform_dir: ../environments/dev/full-pipeline
  #   tests:
  #     - test_pipeline