modules:
  compute:
    terraform_dir: ../environments/dev/compute-only
    tests:
      - test_compute

  api:
    terraform_dir: ../environments/dev/api-only
    tests:
      - test_api

  storage:
    terraform_dir: ../environments/dev/storage-only
    tests:
      - test_s3

  storage-messaging:
    terraform_dir: ../environments/dev/storage-messaging
    tests:
      - test_storage_messaging

  messaging:
    terraform_dir: ../environments/dev/messaging-only
    tests:
      - test_sqs

  worker:
    terraform_dir: ../environments/dev/worker-only
    tests:
      - test_worker

  full-pipeline:
    terraform_dir: ../environments/dev/full-pipeline
    tests:
      - test_pipeline